server:
  port: 8888


spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password : guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/Desktop/config_folder/native-file-repo
        git:
          default-label: master
          uri: https://github.com/wlsgh7608/spring-cloud-config.git
  endpoints:
    web:
      exposure:
        include: health,busrefresh
